#include <iostream>
#include "windows.h"


// Display the exception data and processor context
// captured by Windows at the time the exception is dispatched.
LONG WINAPI handler(struct _EXCEPTION_POINTERS* ExceptionInfo)
{
	// Inspect the exception record generated by the dispatcher.
	printf("Exception code: 0x%X\n", ExceptionInfo->ExceptionRecord->ExceptionCode);
	printf("Exception address: 0x%p\n", ExceptionInfo->ExceptionRecord->ExceptionAddress);
	printf("Number of parameters: %lu\n", ExceptionInfo->ExceptionRecord->NumberParameters);

	// Inspect the CPU context that can later be modified to alter the program's execution flow.
	printf("RIP: %#llx\n", ExceptionInfo->ContextRecord->Rip);
	printf("RSP: %#llx\n", ExceptionInfo->ContextRecord->Rsp);
	printf("RAX: %#llx\n", ExceptionInfo->ContextRecord->Rax);
	printf("RCX: %#llx\n", ExceptionInfo->ContextRecord->Rcx);
	printf("RDX: %#llx\n", ExceptionInfo->ContextRecord->Rdx);
	printf("R8: %#llx\n", ExceptionInfo->ContextRecord->R8);
	printf("R9: %#llx\n", ExceptionInfo->ContextRecord->R9);

	// Handle the generated exception by RaiseException()
	if (ExceptionInfo->ExceptionRecord->ExceptionCode == STATUS_ACCESS_VIOLATION)
	{

		// Resume execution after the exception has been processed.
		return EXCEPTION_CONTINUE_EXECUTION;
	}

	// Forward all other exceptions to the next registered handler.
    return EXCEPTION_CONTINUE_SEARCH;
}

int main()
{
	// Register the vectored exception handler
	PVOID handlerHandle = AddVectoredExceptionHandler(1, handler);

	// Generate an access violation exception to test the handler
    RaiseException(STATUS_ACCESS_VIOLATION, 0, 0, nullptr);

	// Unregister the vectored exception handler
	RemoveVectoredExceptionHandler(handlerHandle);
	return 0;
}

