#include <iostream>
#include "windows.h"

DWORD old = 0;
int* value = nullptr;

LONG WINAPI handler(struct _EXCEPTION_POINTERS* ExceptionInfo) {
    // Handle only guard-page violations generated by this PoC.
    if (ExceptionInfo->ExceptionRecord->ExceptionCode == STATUS_ACCESS_VIOLATION)
    {
        printf("Access violation triggered\n");
        printf("Exception Address: %#llx\n", ExceptionInfo->ExceptionRecord->ExceptionAddress);
        printf("RIP: %#llx\n", ExceptionInfo->ContextRecord->Rip);

        // Restoring page protection to PAGE_READWRITE since unlike PAGE_GUARD, PAGE_NOACCESS will still remain and continue to trigger VEH.
        VirtualProtect(value, sizeof(value), PAGE_READWRITE, &old);
        
        return EXCEPTION_CONTINUE_EXECUTION;
    }

    return EXCEPTION_CONTINUE_SEARCH;
}

int main()
{
    // Allocate one page of readable and writable memory.
    value = static_cast<int*>(VirtualAlloc(nullptr, sizeof(int), MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE));
    *value = 1997;
    

    // Register the handler before accessing guarded memory.
    PVOID handlerHandle = AddVectoredExceptionHandler(1, handler);

    // Apply PAGE_NOACCESS while retaining read/write access.
    VirtualProtect(value, sizeof(int), PAGE_NOACCESS, &old);

    // Attempt to access the memory after applying PAGE_NOACCESS triggers STATUS_ACCESS_VIOLATION.
    printf("Value: %d\n", *value);

    printf("Value after first access: %d\n", *value);

    VirtualFree(value, 0, MEM_RELEASE);
    RemoveVectoredExceptionHandler(handlerHandle);

    return 0;
}
