#include <iostream>
#include "windows.h"



LONG WINAPI handler(struct _EXCEPTION_POINTERS *ExceptionInfo) {
    // Handle only guard-page violations generated by this PoC.
    if (ExceptionInfo->ExceptionRecord->ExceptionCode == STATUS_GUARD_PAGE_VIOLATION)
    {
        printf("Guard Page violation triggered\n");
        printf("Exception Address: %#llx\n", ExceptionInfo->ExceptionRecord->ExceptionAddress);
        printf("RIP: %#llx\n", ExceptionInfo->ContextRecord->Rip);

        // PAGE_GUARD is cleared automatically after the first access,
        // The faulting instruction can be retried successfully.
        return EXCEPTION_CONTINUE_EXECUTION;
    }

    return EXCEPTION_CONTINUE_SEARCH;
}

int main()
{
    // Allocate one page of readable and writable memory.
    int* value = static_cast<int*>(VirtualAlloc(nullptr, sizeof(int), MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE));
    *value = 1997;
    DWORD old = 0;

    // Register the handler before accessing guarded memory.
    PVOID handlerHandle = AddVectoredExceptionHandler(1, handler);

    // Apply PAGE_GUARD while retaining read/write access.
    VirtualProtect(value, sizeof(int), PAGE_READWRITE | PAGE_GUARD, &old);

    // Attempt to access the memory after applying PAGE_GUARD triggers STATUS_GUARD_PAGE_VIOLATION.
    printf("Value: %d\n", *value);

    // PAGE_GUARD is one-shot, so this second access should not fault.
    printf("Value after first access: %d\n", *value);

    VirtualFree(value, 0, MEM_RELEASE);
    RemoveVectoredExceptionHandler(handlerHandle);

    return 0;
}
